# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from time import sleep

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 550)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 550))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(10, 60, 771, 161))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(370, 10, 71, 31))
        self.label_2.setStyleSheet("font: 63 14pt \"Segoe UI Variable Text Semibold\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 320, 71, 31))
        self.label_3.setStyleSheet("font: 63 14pt \"Segoe UI Variable Text Semibold\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(150, 318, 71, 31))
        self.label_4.setStyleSheet("font: 63 14pt \"Segoe UI Variable Text Semibold\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(310, 320, 71, 31))
        self.label_5.setStyleSheet("font: 63 14pt \"Segoe UI Variable Text Semibold\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(400, 320, 71, 31))
        self.label_6.setStyleSheet("font: 63 14pt \"Segoe UI Variable Text Semibold\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(540, 322, 71, 31))
        self.label_7.setStyleSheet("font: 63 14pt \"Segoe UI Variable Text Semibold\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(630, 318, 71, 31))
        self.label_8.setStyleSheet("font: 63 14pt \"Segoe UI Variable Text Semibold\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(60, 392, 71, 31))
        self.label_9.setStyleSheet("font: 63 14pt \"Segoe UI Variable Text Semibold\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(150, 390, 71, 31))
        self.label_10.setStyleSheet("font: 63 14pt \"Segoe UI Variable Text Semibold\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(310, 392, 71, 31))
        self.label_11.setStyleSheet("font: 63 14pt \"Segoe UI Variable Text Semibold\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(400, 392, 71, 31))
        self.label_12.setStyleSheet("font: 63 14pt \"Segoe UI Variable Text Semibold\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(190, 320, 71, 31))
        self.label_13.setStyleSheet("font: 63 14pt \"Segoe UI Variable Text Semibold\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(670, 320, 71, 31))
        self.label_14.setStyleSheet("font: 63 14pt \"Segoe UI Variable Text Semibold\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(440, 320, 71, 31))
        self.label_15.setStyleSheet("font: 63 14pt \"Segoe UI Variable Text Semibold\";")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(190, 390, 71, 31))
        self.label_16.setStyleSheet("font: 63 14pt \"Segoe UI Variable Text Semibold\";")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(440, 390, 71, 31))
        self.label_17.setStyleSheet("font: 63 14pt \"Segoe UI Variable Text Semibold\";")
        self.label_17.setObjectName("label_17")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(350, 240, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.extract_values)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 490, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.rating)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def extract_values(self):
        mytext = self.textEdit.toPlainText()
        a = mytext.find('BMD FILE SEL')
        b = mytext.find('HOMEBATCHHANDLER')
        c = mytext[a:b]
        res = [int(i) for i in c.split() if i.isdigit()]

        self.label_13.setText(str(res[0]))
        self.label_15.setText(str(res[1]))
        self.label_14.setText(str(res[4]))
        self.label_16.setText(str(res[6]))
        self.label_17.setText(str(res[7]))

    def rating(self):
        driver = webdriver.Firefox(executable_path="D:\\Atharva\\Rating\\geckodriver.exe")
        driver.get("http://10.97.196.18:8080/vfgroperation/jsp/menu.jsp")

        dropdown = driver.find_element(By.NAME,"combo")
        dd = Select(dropdown)

        dd.select_by_visible_text('Voice CDR Selection')

        driver.find_element(By.XPATH, "/html/body/center/form/table/tbody/tr[1]/td[2]/table/tbody/tr[5]/td[1]/table/tbody/tr[3]").click()
        sleep(5)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Rating"))
        self.label_2.setText(_translate("Dialog", "Rating"))
        self.label_3.setText(_translate("Dialog", "VOICE"))
        self.label_4.setText(_translate("Dialog", ":"))
        self.label_5.setText(_translate("Dialog", "SMS"))
        self.label_6.setText(_translate("Dialog", ":"))
        self.label_7.setText(_translate("Dialog", "IMS"))
        self.label_8.setText(_translate("Dialog", ":"))
        self.label_9.setText(_translate("Dialog", "CYTA"))
        self.label_10.setText(_translate("Dialog", ":"))
        self.label_11.setText(_translate("Dialog", "GPRS"))
        self.label_12.setText(_translate("Dialog", ":"))
        self.label_13.setText(_translate("Dialog", "0"))
        self.label_14.setText(_translate("Dialog", "0"))
        self.label_15.setText(_translate("Dialog", "0"))
        self.label_16.setText(_translate("Dialog", "0"))
        self.label_17.setText(_translate("Dialog", "0"))
        self.pushButton.setText(_translate("Dialog", "Extract Values"))
        self.pushButton_2.setText(_translate("Dialog", "Start Rating"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())